kernel:
  image: linuxkit/kernel:5.6.11-db4bb0a764332e161ac1df8eb2e5b9de183bc87f-amd64
  cmdline: "console=tty0"
init:
  - linuxkit/init:8f1e6a0747acbbb4d7e24dc98f97faa8d1c6cec7
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:de1b18eed76a266baa3092e5c154c84f595e56da
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
  - name: sysfs
    image: linuxkit/sysfs:c3bdb00c5e23bf566d294bafd5f7890ca319056f
  - name: rngd1
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
    command: ["/sbin/rngd", "-1"]
  - name: format
    image: linuxkit/format:7efa07559dd23cb4dbebfd3ab48c50fd33625918
  - name: mount
    image: linuxkit/mount:422b219bb1c7051096126ac83e6dcc8b2f3f1176
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
  - name: ntpd
    image: linuxkit/openntpd:d6c36ac367ed26a6eeffd8db78334d9f8041b038
  - name: sshd
    image: linuxkit/sshd:4696ba61c3ec091328e1c14857d77e675802342f
  - name: docker
    image: docker:20.10.18-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
  - path: root/.ssh/authorized_keys
    mode: "0600"
    optional: true
    contents: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8+N80pKix1zFTVUq2nNO1NjIX+yAEYVwsKGg0OJ5H6gvd1lbEJ5FxAVz1uMY+i7bbIWEBG6YTx0Hap3O1XoNSFGUcutmc8z02F+EvtM1IVIV3MA6CW11QDPKY1RftD2JVr2gIPo3S3SkqbKqpeD+pkJvfXM03M/b8NCSdYC2WICp9ubylnzLQ/3TRKh30qKxWdUdFAOVsfFf6u0PS4rhh36mjxnTb0J5Os9r+Yrd7gi3Y/Ejv3xbfhqM2N4VJjWYj3hBfv7Um2f4KL54UzmenNVO6RiqtYehirGv7noJj/iTgPLcTuonPlv4Dq5UxkSdSiqgvtqEJfEf02cP2tzBFioPgkKQO3b23W0tBEqii8W+DJIMz+rbKD/mysoWwtPFj5G9HxTZE8mnIuByxd+OOSL5nUZndC2zzLACEoJ2jJ5n8Q9lyk3lRvl5aVWqhx1CEgtiuHz7OdmeXeFJUN8SJY0FTHS6YuwROPCRqomVmSOSEbxjxgVHQxCbyoa1YLFs= root@linuxkit'
